// Generated by CoffeeScript 1.10.0
var Rel, assert;

assert = require('chai').assert;

Rel = require('../lib/rel');

describe('Integrating rel', function() {
  it('should perform a users find', function() {
    var users;
    users = new Rel.Table('users');
    return assert.equal(users.where(users.column('name').eq('amy')).toSql(), 'SELECT FROM "users" WHERE "users"."name" = \'amy\'');
  });
  it('should run through the first example on the readme', function() {
    var users;
    users = new Rel.Table('users');
    return assert.equal(users.project(Rel.star()).toSql(), 'SELECT * FROM "users"');
  });
  return it('testing the or example', function() {
    var users;
    users = new Rel.Table('users');
    return users.where(users.column('name').eq('bob').or(users.column('age').lt(25)));
  });
});
