// Generated by CoffeeScript 1.10.0
var Attribute, exports, u;

u = require('underscore');

Attribute = (function() {
  function Attribute(relation, name) {
    var Expressions, Predications;
    this.relation = relation;
    this.name = name;
    Expressions = require('./expressions');
    Predications = require('./predications');
    u(this).extend(Expressions);
    u(this).extend(Predications);
  }

  return Attribute;

})();

exports = module.exports = Attribute;
