// Generated by CoffeeScript 1.10.0
var Crud, InsertManager, SqlLiteral, UpdateManager, exports;

InsertManager = require('./insert-manager');

UpdateManager = require('./update-manager');

SqlLiteral = require('./nodes/sql-literal');

Crud = (function() {
  function Crud() {}

  Crud.prototype.compileInsert = function(values) {
    var im;
    im = this.createInsert();
    im.insert(values);
    return im;
  };

  Crud.prototype.createInsert = function() {
    return new InsertManager();
  };

  Crud.prototype.compileDelete = function() {
    var dm;
    dm = new DeleteManager();
    dm.wheres(this.ctx.wheres);
    dm.from(this.ctx.froms);
    return dm;
  };

  Crud.prototype.compileUpdate = function(values) {
    var relation, um;
    um = new UpdateManager();
    relation = values.constructor === SqlLiteral ? this.ctx.from : values[0][0].relation;
    um.table(relation);
    um.set(values);
    if (this.ast.limit != null) {
      um.take(this.ast.limit.expr);
    }
    um.order(this.ast.orders);
    um.wheres = this.ctx.wheres;
    return um;
  };

  return Crud;

})();

exports = module.exports = Crud;
