// Generated by CoffeeScript 1.10.0
var Expressions, Nodes, exports;

Nodes = require('./nodes/nodes');

Expressions = {
  count: function(distinct) {
    if (distinct == null) {
      distinct = false;
    }
    return new Nodes.Count([this], distinct);
  },
  sum: function() {
    return new Nodes.Sum([this], new Nodes.SqlLiteral('sum_id'));
  },
  maximum: function() {
    return new Nodes.Max([this], new (Nodes.SqlLiteral('max_id')));
  },
  minimum: function() {
    return new Nodes.Min([this], new (Nodes.SqlLiteral('min_id')));
  },
  average: function() {
    return new Nodes.Avg([this], new (Nodes.SqlLiteral('avg_id')));
  }
};

exports = module.exports = Expressions;
