// Generated by CoffeeScript 1.10.0
var Range, exports;

Range = (function() {
  function Range(start, finish) {
    this.start = start;
    this.finish = finish;
  }

  return Range;

})();

exports = module.exports = Range;
