// Generated by CoffeeScript 1.10.0
var Dot, OrderClauses, Postgresql, ToSql, Visitors, WhereSql, exports,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Dot = require('./visitors/dot');

Postgresql = require('./visitors/postgresql');

ToSql = require('./visitors/to-sql');

Visitors = {
  Dot: Dot,
  visitor: function() {
    return new Postgresql();
  },
  JoinSql: {
    visitRelNodesSelectCore: function(o) {
      return (o.source.right.map((function(_this) {
        return function(j) {
          return _this.visit(j);
        };
      })(this))).join(' ');
    }
  },
  OrderClauses: OrderClauses = (function(superClass) {
    extend(OrderClauses, superClass);

    function OrderClauses() {
      return OrderClauses.__super__.constructor.apply(this, arguments);
    }

    OrderClauses.prototype.visitRelNodesSelectStatement = function(o) {
      return o.orders.map((function(_this) {
        return function(x) {
          return _this.visit(x);
        };
      })(this));
    };

    return OrderClauses;

  })(ToSql),
  WhereSql: WhereSql = (function(superClass) {
    extend(WhereSql, superClass);

    function WhereSql() {
      return WhereSql.__super__.constructor.apply(this, arguments);
    }

    WhereSql.prototype.visitRelNodesSelectCore = function(o) {
      return "WHERE " + ((o.wheres.map((function(_this) {
        return function(x) {
          return _this.visit(x);
        };
      })(this))).join(' AND '));
    };

    return WhereSql;

  })(ToSql)
};

exports = module.exports = Visitors;
