// Generated by CoffeeScript 1.10.0
var ConstLit, SqlLiteral, Unary, exports, u,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  slice = [].slice;

u = require('underscore');

Unary = require('./unary');

SqlLiteral = require('./sql-literal');

ConstLit = (function(superClass) {
  extend(ConstLit, superClass);

  function ConstLit() {
    var Expressions, Predications, args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    ConstLit.__super__.constructor.apply(this, args);
    Expressions = require('../expressions');
    Predications = require('../predications');
    u(this).extend(Expressions);
    u(this).extend(Predications);
  }

  return ConstLit;

})(Unary);

exports = module.exports = ConstLit;
