// Generated by CoffeeScript 1.10.0
var SqlLiteral, exports, u;

u = require('underscore');

SqlLiteral = (function() {
  function SqlLiteral(value) {
    var Expressions, Predications;
    this.value = value;
    Expressions = require('../expressions');
    Predications = require('../predications');
    u(this).extend(Expressions);
    u(this).extend(SqlLiteral);
  }

  SqlLiteral.prototype.toString = function() {
    return this.value;
  };

  return SqlLiteral;

})();

exports = module.exports = SqlLiteral;
