// Generated by CoffeeScript 1.10.0
var Attribute, TableAlias, exports;

Attribute = require('../attribute');

TableAlias = (function() {
  function TableAlias(left, right) {
    this.left = left;
    this.right = right;
  }

  TableAlias.prototype.name = function() {
    return this.right;
  };

  TableAlias.prototype.relation = function() {
    return this.left;
  };

  TableAlias.prototype.tableAlias = function() {
    return this.relation().name;
  };

  TableAlias.prototype.tableName = function() {
    return this.relation().name;
  };

  return TableAlias;

})();

exports = module.exports = TableAlias;
