// Generated by CoffeeScript 1.10.0
var Node, Unary, exports,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Node = require('./node');

Unary = (function(superClass) {
  extend(Unary, superClass);

  function Unary(expr) {
    this.expr = expr;
    this.value = this.expr;
  }

  return Unary;

})(Node);

exports = module.exports = Unary;
