// Generated by CoffeeScript 1.10.0
var Visitor, exports;

Visitor = (function() {
  function Visitor() {}

  Visitor.prototype.accept = function(object) {
    return this.visit(object);
  };

  Visitor.prototype.visit = function(object) {
    var ref, type;
    type = (ref = object != null ? object.constructor.name : void 0) != null ? ref : 'Null';
    return this["visitRelNodes" + type](object);
  };

  return Visitor;

})();

exports = module.exports = Visitor;
